- src/main/java/ti4/draft/DraftItem.java
- src/main/java/ti4/draft/FrankenDraft.java
- src/main/java/ti4/draft/items/AbilityDraftItem.java
- src/main/java/ti4/draft/items/AgentDraftItem.java
- src/main/java/ti4/draft/items/BlueTileDraftItem.java
- src/main/java/ti4/draft/items/CommanderDraftItem.java
- src/main/java/ti4/draft/items/CommoditiesDraftItem.java
- src/main/java/ti4/draft/items/FlagshipDraftItem.java
- src/main/java/ti4/draft/items/HeroDraftItem.java
- src/main/java/ti4/draft/items/HomeSystemDraftItem.java
- src/main/java/ti4/draft/items/MechDraftItem.java
- src/main/java/ti4/draft/items/PNDraftItem.java
- src/main/java/ti4/draft/items/RedTileDraftItem.java
- src/main/java/ti4/draft/items/SpeakerOrderDraftItem.java
- src/main/java/ti4/draft/items/StartingFleetDraftItem.java
- src/main/java/ti4/draft/items/StartingTechDraftItem.java
- src/main/java/ti4/draft/items/TechDraftItem.java
A recent update to Franken caused a bunch of log spam when saving to JSON. This adds JSONIgnore to a bunch of methods so they don't get serialized.
> Fix Log Spam

- src/test/java/ti4/map/LeaderTest.java
This is an example Jackson serialization tests which will ensure `Leader` is always serializable. I intend to spread this pattern into all objects which eventually get serialized to bring stability to our save/restore process.
In these series of tests, I confirm that object data survives a save/restore cycle and the tests will automatically fail should anyone add new fields which suddenly appear in the JSON model.
Validated that tests fail when I add a new property or function which causes a field to be added to the JSON model. Also confirmed null values are caught by the field detection logic.
Ran build and new tests:
```
docker build -t tibot .
```
> Leader.java Jackson Serialization Tests

- src/main/java/ti4/helpers/Units.java
- src/test/java/ti4/helpers/UnitsTest.java
- src/test/java/ti4/map/LeaderTest.java
- src/test/java/ti4/testUtils/JacksonConfigurationException.java
- src/test/java/ti4/testUtils/JsonValidator.java
More serialization tests, this time for `UnitKey`.
`UnitKey` is causing us issues as it's being used as a key in Java maps which messes up serialization. JSON only allows map keys to be strings, causing issues we we attempt to deserialize back to a Java map.
This ensures we can at least serialize UnitKey which was taking on tons of extra fields that I had to drop.
Next step will be to modify the serialization process to get this working when `UnitKey` is used as a map key.
```
docker build -t tibot .
```
> Basic JSON serialization tests for `UnitKey`

- src/main/java/ti4/helpers/Units.java
- src/main/java/ti4/json/ObjectMapperFactory.java
- src/main/java/ti4/json/UnitKeyMapKeyDeserializer.java
- src/main/java/ti4/json/UnitKeyMapKeySerializer.java
- src/main/java/ti4/map/UnitHolder.java
- src/test/java/ti4/map/SpaceTest.java
- src/test/java/ti4/testUtils/JsonValidator.java
Because `UnitKey` objects are used as keys within Java maps, we need special serialization logic for them as JSON map keys can only be strings. So we must make the "key" a JSON string which we then unwrap when deserializing.
Before this, Jackson was using `UnitKey.toString()` to convert the object key into a string which is not at all what we want.
I tried getting annotations working to add the key serializers/deserializers but I could never get the deserializer to trigger. Only way I got it working was to attach them to the `ObjectMapper`.
At some point we will need to do a pass and update all `ObjectMapper`'s to use the factory I created. Otherwise they will fail to convert objects.
```
docker build -t tibot .
```
> Space JSON Serialization with Map-key special logic

- src/main/resources/data/units/absol.json
- src/main/resources/data/units/ds.json
- src/main/resources/data/units/miltymod.json
- src/main/resources/data/units/units.json
Adds ability text for Dreadnought II variants, Naalu Fighter II, and War Sun.
~~Only addresses the base game & PoK units. The various mods have at least some of the same problems, but i don't know where to find authoritative sources for those yet. i'll get those in another pass hopefully.~~
Includes MiltyMod, Absol, and Discordant Stars variants, where applicable.
Also adds the Ghemina Raiders' Combat Transport II's ability, which was also missing.
> Add missing unit upgrade ability text

- src/main/resources/data/units/miltymod.json
This erroneously read Prototype War Sun II.
> Correct the tier number for MiltyMod Prototype War Sun I

- src/main/resources/data/relics/absol.json
Scepter was misspelled, lattice was misspelled, the quotation marks in Shard Of The Throne 1 were odd.
I checked these against some card images in an attempt to confirm that the errors were here and not in the source.
> Fix typos in Absol's Relics

- src/main/java/ti4/model/RelicModel.java
- src/main/resources/data/relics/absol.json
- src/main/resources/data/relics/codexii.json
- src/main/resources/data/relics/pok.json
Allows formatting the nested emphasis in The Prophet's Tears' flavour text. Everything else should be unchanged.
> Move relic flavour text formatting into the data files

- src/main/java/ti4/model/ExploreModel.java
- src/main/resources/data/explores/explores.json
For no particular reason.
Covers PoK, codex 3, and Discordant Stars.
The field is unused at the moment.
> Add flavor text for explore cards

- src/main/java/ti4/MessageListener.java
Closes #1270.
I had to do at least a little refactoring in order to read the code, but i tried to keep it to a minimum.
Changes the substring logic to produce empty strings instead of StringIndexOutOfBoundsExceptions. This lets empty whispers be sent and received without error.
Adds a check to catch empty whispers and log them instead of sending them.
~~(I think not sending them is better, because otherwise accidentally omitting the space between the address and the message could trigger one of the more confusing bugs.)~~ (Nevermind, only makes a difference for single-word messages.)
> Handle empty whispers

- src/main/java/ti4/helpers/Emojis.java
Mordai II, Vefut II, Retillion, and the locked Mallice variant have emojis, but are still rendered as Sem-Lores, because their ids were missing or aliases were used in `Emojis.java`.
> Link emojis for 4 planets

- src/main/java/ti4/commands/explore/SendFragments.java
- src/main/java/ti4/helpers/FoWHelper.java
In FOW mode, sending a fragment to another player gives duplicate message to the receiver: 
Restricted sending the first message to non-fow-mode since FOW specifc check and message is sent later.
In FOW, when a previously seen tile gets fogged, tile number overlaps with Round 2 (or whatever round you saw the tile last).
Shortened Round to Rnd to fix this.
> Small FOW-mode fixes

- src/main/java/ti4/buttons/ButtonListener.java
- src/main/java/ti4/commands/cardsac/ACInfo.java
- src/main/java/ti4/commands/cardsac/PlayAC.java
- src/main/java/ti4/commands/combat/StartCombat.java
- src/main/java/ti4/commands/explore/ExpPlanet.java
- src/main/java/ti4/commands/planet/PlanetAdd.java
- src/main/java/ti4/commands/player/SCPlay.java
- src/main/java/ti4/commands/player/TurnStart.java
- src/main/java/ti4/commands/uncategorized/CardsInfo.java
- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/helpers/ButtonHelperAbilities.java
- src/main/java/ti4/helpers/ButtonHelperAgents.java
- src/main/java/ti4/helpers/ButtonHelperFactionSpecific.java
- src/main/java/ti4/helpers/ButtonHelperModifyUnits.java
- src/main/java/ti4/helpers/ButtonHelperTacticalAction.java
- src/main/java/ti4/helpers/Helper.java
- src/main/java/ti4/map/Player.java
This update names all of the agents in the game everywhere (mostly?) they are used, in the form e.g. "Carth of Golden Sands (Hacan Agent)". More importantly, when Yssaril copies an agent, it will prefix "Clever Clever" to the agent name e.g. "Clever Clever Carth of Golden Sands (Hacan Agent)", to make it clear that it is a copy being used.
The code uses `player.hasUnexhaustedLeader("yssarilagent")`. This may cause weirdness in Franken if somebody has both Ssruu and The Company. In addition, if the agent is referenced in a multi-step process, and Ssruu is exhausted in one of the first steps, then the prefix will be dropped for the later steps. Furthermore, there's a few functions where the owner of the agent isn't explicitly passed as an argument, especially for a few of the three-way …
> Clever Clever Ssruu

- src/main/java/ti4/commands/fow/AddAdjacencyOverrideList.java
- src/main/java/ti4/commands/fow/FOWCommand.java
- src/main/java/ti4/helpers/Constants.java
When building a lot of maps and using a lot of adjacency overrides, it is a pain to add them one by one. 
Added a command to add all of them at once using pattern "PrimaryTile:Direction:SecondaryTile 101:nw:202 ..."
This also makes it possible for you to store the string and just copy-paste it to add all adjacencies in similar vein of map add_tile_list.
> AddAdjacencyOverrideList to add all adjacencies with one command

- src/main/java/ti4/commands/cardsso/ListAllScored.java
- src/main/java/ti4/commands/status/POInfo.java
FoW checks for
/so list_scored - to only show SOs player can see
/status po_info include_scored: true - to show only faction emojies player can see
> Limit visibility of scored objectives in FoW

- src/main/java/ti4/buttons/ButtonListener.java
- src/main/java/ti4/commands/player/TurnEnd.java
Added checks for End of Turn in FoW.
If pressing End Turn button out of turn:
Trying to End Turn with a command:
Added End of Turn message (I've been asked how does one know they've ended their turn, and I've had to answer "if you see double ping message followed by next player notification, then that means you've ended your turn"). This is more clear.
> Prevent accidental end of turns in FoW

- src/main/java/ti4/commands/player/TurnEnd.java
- src/main/java/ti4/commands/status/Cleanup.java
- src/main/java/ti4/helpers/ButtonHelper.java
Had a situation where a player activated a system containing one player's ships, and another player's ground forces. They returned a promissory note to both players, but one was an Alliance, and the return message didn't show whose Alliance was being returned. This should add the faction emoji before the promissory note name to clear this up. Also, knowing the faction that the Alliance belonged to is useful information, given that the ability granted by the Alliance is different for each faction.
> Add faction emoji to promissory note return message

- src/main/java/ti4/AsyncTI4DiscordBot.java
- src/main/java/ti4/commands/fow/RemoveFogTile.java
When 💩 hits the fan in FoW and a player sees more than they are supposed to, it is a pain to remove shown tiles one by one. Also, GM can't do that for the player. They have to do it.
Changed RemoveFogTile so that multiple tiles can be removed at once. And allow the command to be used for someone else.
> Allow /fow remove_fog_tile to remove multiple tiles at once for another player

- src/main/java/ti4/commands/franken/StartFrankenDraft.java
- src/main/java/ti4/draft/BagDraft.java
- src/main/java/ti4/draft/OnePickFrankenDraft.java
- src/main/java/ti4/helpers/Constants.java
- src/main/java/ti4/helpers/FrankenDraftHelper.java
Our group thinks picking 3 from the first bag is unbalanced and we want to pick only 1 at a time.
Ideally would've like to make it a choice of how many to pick from first bag and how many from the following bags, but as we currently only save the draft name and not any options for it, felt this is more convenient solution at the moment.
Also don't really like that command has two options which only one can used (powred or onepick). More futureproof could've been /franken start_franken_draft mode: default/powered/onepick. But then tooltip about the mode woudn't be visible.
Thoughts?
> Franken draft mode to pick 1 at a time

- src/main/java/ti4/autocomplete/AutoCompleteProvider.java
- src/main/java/ti4/commands/franken/StartFrankenDraft.java
- src/main/java/ti4/helpers/Constants.java
Changed /franken start_franken_draft from having multiple special draft options with true/false to use draft_mode option with autocomplete to better support more special draft options later on.
> Franken special draft option to use enums and autocomplete

- src/main/java/ti4/commands/tokens/AddRemoveToken.java
As this already supports multiple players, added similar support for multiple tiles. Did a lot of testing, but since several commands extend this one and this affects all of them, I'd like a review to confirm this is ok to do. :)
Main benefit for custom maps to be able to add all custom wormholes at once, 
or to remove them
But works with any token.
Also allows adding or removing multiple ccs if there is a reason to
> Support for multiple tiles for add/remove token

- src/main/java/ti4/commands/fow/RemoveFogTile.java
Elsewhere comma is used to separate multiple arguments so do that here as well.
> Comma instead of space to separate tiles

- src/main/java/ti4/commands/fow/Whisper.java
When using anon:y in /fow whisper, recipient isn't pinged. Changed the message to be similar when using without anon:y, only [REDACT] the sender.
Ping is needed in FoW when announcing AC targets anonymously. Easy to miss otherwise.
> Ping recipient when whispering with anon:y

- src/main/java/ti4/commands/franken/FrankenCommand.java
- src/main/java/ti4/commands/franken/SetHomeSystemPosition.java
- src/main/java/ti4/helpers/Constants.java
- src/main/java/ti4/map/GameSaveLoadManager.java
- src/main/java/ti4/map/Player.java
An override setting to explicitly set home system position in Franken. 
Default behaviour persists unless homeSystemPosition is set. In that case use that one.
This allows moving stats_anchors to better locations so player information won't overlap the map mainly in Franken-FoW where they can't be moved atm due to visibility checks based on HS. Currently an issue for example in my fow180.
> SetHomeSystemPosition command to set HS explicitly in Franken

- src/main/java/ti4/commands/player/SCPick.java
- src/main/java/ti4/commands/player/Stats.java
Checks and Balances reveals player information in FoW.
It told the player selecting the SC the name of the player they were giving it to.
It told the receiving player the faction emoji of player doing the selection.
> Fix Checks and Balances to not reveal player info in FoW

- src/main/java/ti4/commands/agenda/ListVoteCount.java
- src/main/java/ti4/commands/custom/CustomizationOptions.java
- src/main/java/ti4/commands/fow/FOWCommand.java
- src/main/java/ti4/commands/fow/FOWOptions.java
- src/main/java/ti4/commands/game/Info.java
- src/main/java/ti4/generator/MapGenerator.java
- src/main/java/ti4/helpers/Constants.java
- src/main/java/ti4/map/Game.java
- src/main/java/ti4/map/GameSaveLoadManager.java
Added a command /fow fow_options to put all fow settings to one place and make it easy to add more if needed in the future.
- Moved the setting to hide player names from /custom customization to /fow fow_options
- Added an option to hide total votes in agenda
- Show set fow options in /game info if game is fow
> Fow options command for optional settings

- src/main/java/ti4/helpers/ButtonHelper.java
Relic was removed before resolving it, which made absol Dynamis Core to first reduce total commodities and thus giving wrong number of TGs.
> Remove relic AFTER resolving it to fix Dynamis Core

- src/main/java/ti4/commands/agenda/RevealAgenda.java
- src/main/java/ti4/commands/player/TurnEnd.java
- src/main/java/ti4/generator/MapGenerator.java
- src/main/java/ti4/helpers/ButtonHelper.java
Now the banners should always display in the actions channel, instead of the map updates thread for the Action Phase banner.
Also, the round number will display in words on the banner for rounds zero to twenty inclusive, expanded from round one to nine inclusive. Additionally, the round number will display in digits for outside this range. Imperium Rex happens at the end of round nine RAW, but homebrew might create an extended game, so this will show up in that case.
> Phase Banner Updates

- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/helpers/ButtonHelperFactionSpecific.java
- src/main/java/ti4/helpers/ButtonHelperHeroes.java
This adds the tile position to the gravity rift rolling messages. The main motivation behind this is that it will trigger on the Vuil'raith hero. At the moment, after all the buttons have been pressed, there's just a list of ships. Somebody who was not online at the time would have a hard time knowing where the lost ships were previously located.
> Tile Positions In Gravity Rift Rift Loss Messages

- src/main/java/ti4/commands/game/GameEnd.java
- src/main/java/ti4/map/Game.java
* Post same game summary to fow-war-stories like happens with pdb games in the-pbd-chronicles, but without the map and GMs added
* Create a similar thread for end-of-game discussions as for pdb-games, but also without the map and make this thread private
* Added deleting the GM role when game ends.
* Fixed log spam for end-of-game messages trying to go to deleted fow channels by delaying the deletion
> Create FoW end-of-game summary

- src/main/java/ti4/MessageListener.java
- src/main/java/ti4/commands/combat/StartCombat.java
Constantly players who see the combat, but are not participants of it, are confused about the combat thread created for them in FoW to spectate the interaction.
So for spectators, create a thread without combat buttons nor steps-for-combat -message.
> Spectator specific thread for FoW combats

- src/main/java/ti4/commands/fow/FOWCommand.java
- src/main/java/ti4/commands/fow/ShowGameAsPlayer.java
- src/main/java/ti4/generator/MapGenerator.java
- src/main/java/ti4/helpers/Constants.java
A suggestion for a command to view FoW as a specific player. 
Don't like the way to extend SlashCommandInteractionEvent to override getUser, but this seemed the most clean way. Didn't want to invent a whole new way to pass the User to MapGenerator just for this feature.
> Command to view FoW as specific player

- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/map/Tile.java
- src/main/java/ti4/model/UnitModel.java
- src/main/resources/data/units/absol.json
Absol's mod's space dock upgrades allow the player to ignore some number of non-fighter ships when 
checking fleet pool size.
This commit allows that feature to be added to any unit by adding the `fleetSupplyBonus` to the unit's 
JSON model definition.X
> fix: updated Absol's space docks to account for ignoring non-fighter ships in fleet pool checks

- src/main/java/ti4/buttons/ButtonListener.java
- src/main/java/ti4/buttons/Buttons.java
- src/main/java/ti4/commands/player/Pass.java
- src/main/java/ti4/commands/tech/GetTechButton.java
- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/helpers/Helper.java
- src/main/java/ti4/map/Player.java
- src/main/resources/data/technologies/absol.json
- **fix: missing War Sun button on production for Muaat players on Absol's Techs & Mechs**
- **fix: incorrect tech requirement's for Absol's Mahact Crimson Legionnaire II**
- **fix: bug where Absol's AI Development Algorithm's post-pass tech research is paid for with Resources instead of Influence**
- **fix: bug where Absol's AI Development Algorithm post-pass ability provided buttons for all tech types instead of just units**
> absol tech fixes 14oct24

- src/main/java/ti4/MessageListener.java
- src/main/java/ti4/commands/combat/StartCombat.java
- src/main/java/ti4/commands/game/GameEnd.java
- src/main/java/ti4/commands/relic/RelicSendFragments.java
- src/main/java/ti4/helpers/async/RoundSummaryHelper.java
* Added a check for existing spectator thread, so spectating space combat followed by invasion uses the same thread like it does for the actual combat thread. Currently it was creating a new one for invasion.
* Allow non-players to create EndOfRound summaries. So basically GM can use `endofround1 Message` to save the first summary. Buttons to add/modify them are given in reply so after the first one, they can use the buttons too. 
* Used UserName instead of Faction for the key to save them
* Used Good Doggos instead of Faction Emoji
* Allowed the use of `/combat combat_roll` in channels not starting with the game name. If it is used in a thread and the parent channel name is valid game, then it's allowed.
* Helps a lot in FoW if player-to-player private threads can run that to do PDS …
> Fow improvements

- src/main/java/ti4/commands/planet/PlanetAddRemove.java
In #fow181 player has for whatever reason two instances of Rial Archon `rialarchon, rialarhon`. 
Added a check to be able to remove an invalid planet from player.
> Allow removing an invalid planet from player

- src/main/java/ti4/commands2/search/SearchTilesSubcommand.java
- src/main/java/ti4/model/TileModel.java
Enables filtering tiles in the tile search by the number of planets on the tile. This allows for example to find all multi-planet systems by searching with `min_num_planets = 2`, or to find all systems with exactly 3 planets by searching with `min_num_planets = 3, max_num_planets =3`.
**NOT currently tested locally (I need to configure Discord developer mode)**
> Allow searching tiles based on number of planets

- src/main/java/ti4/helpers/CombatMessageHelper.java
This will show a blue dice whenever the J.N.S. Hylarim rolls a 9 or 10, and thus triggers its ability to produce two additional hits. In theory, if the Jol-Nar player has an additional -2 beyond FRAGILE, a 9 will still show as grey ¯\\\_(ツ)\_/¯.
> Use blue dice for J.N.S. Hylarim critical hits

- src/main/java/ti4/commands2/player/SCPick.java
- src/main/java/ti4/commands2/player/SCUnpick.java
- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/helpers/ButtonHelperActionCards.java
- src/main/java/ti4/message/MessageHelper.java
- src/main/java/ti4/service/game/StartPhaseService.java
- src/main/java/ti4/service/strategycard/PickStrategyCardService.java
- src/main/java/ti4/service/tech/PlayerTechService.java
- src/main/java/ti4/service/turn/StartTurnService.java
Currently, the bot says `[player] is UP NEXT` at the start of their turn. However, on the map, the active player is marked `ACTIVE` and the next player in initiative order is marked `NEXT UP`. This change primarily changes the former message to be more explicit that it is the player's turn *now*.
The player who is next in initiative order is also shown in the start of turn message (if not fog-of-war), but they are not pinged. The message changes if all other players have passed. In addition, the buttons for doing the turn action are moved below the pending strategy cards etc, so that the message can be resolved top-to-bottom (though in the example below, the strategy cards were popped in initiative order, so ideally Leadership would be up the top).
> Change Start-Of-Turn Message

- src/main/java/ti4/commands2/player/SCPick.java
- src/main/java/ti4/commands2/user/SetPingOnNextTurn.java
- src/main/java/ti4/commands2/user/UserCommand.java
- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/service/game/StartPhaseService.java
- src/main/java/ti4/service/player/PingOnNextTurn.java
- src/main/java/ti4/service/statistics/game/WinningPathsStatisticsService.java
- src/main/java/ti4/service/strategycard/PickStrategyCardService.java
- src/main/java/ti4/service/tech/PlayerTechService.java
- src/main/java/ti4/service/turn/StartTurnService.java
- src/main/java/ti4/settings/users/UserSettings.java
Adds a `/user set_ping_on_next_turn` command, which if set true, will ping a player when the player before them starts their turn.
> Ping on next turn

- src/main/java/ti4/AsyncTI4DiscordBot.java
- src/main/java/ti4/commands/game/Replace.java
MiltyDraftManager was throwing a null pointer when it tried to loop over the players using its updated copy of userIds because we never updated the Game objects Map of players by id to have the new userId in it.
> Get replacement mid-milty draft working again

- src/main/java/ti4/helpers/ButtonHelperModifyUnits.java
- src/main/java/ti4/helpers/ShipRepairComparator.java
- src/test/java/ti4/helpers/ButtonHelperModifyUnitsTest.java
Fix for #2699
Issue was in `#autoAssignSpaceCombatHits` when `justSummarizing == true` , destroyed units are not tracked before reaching final duranium check. 
- Added a map to track damaged units instead
- Added sort by preferred repair order (opposite hit order assignment).
I went pretty overboard on test cases, it was just faster for me to test personally. I am open to whatever feedback and best practices the devs prefer.
> Duranium Armor summary fix & repair order automation

- src/main/java/ti4/commands/cardsac/DrawSpecificAC.java
`/ac draw_specific_ac` was drawing and then comparing count with itself to determine if a card was drawn.  Moved current count variable to before the player draws a card.
> Fix /ac draw_specific_ac logic

- src/main/resources/data/units/pok.json
Added image links to POK units as available on ti4ultimate.com.
This change only adds upgrades and mechs, as ti4ultimate does not host individual unit cards of non-upgraded units (i.e. faction specific base units and flagships)
> Added image links to POK units

- src/main/resources/data/technologies/absol.json
The PoK version of this tech includes a description of Custodia Vigilia legendary ability. Adding this text to the Absol version makes it clear that the Custodia Vigilia legendary ability hasn't changed.
> Updating the Absol IIHQ text to match the pok version

- src/main/java/ti4/buttons/handlers/game/CreateGameButtonHandler.java
getLastGameName defaults to "pdb1" when there hasn't been any games yet. And of course there are no roles in that case. This leads to the early termination.
This PR updates the check so that "lastGame" has to be a reasonable value before checking for orphaned roles.
> Create Game: Handle 0 "last game" instances

- src/main/resources/data/franken_errata/pok.json
- Alphabetized `franken_errat/pok.json` for comparison with [the luminous spreadsheet](https://docs.google.com/spreadsheets/d/1zxe2Q5ICCiEOaABhjk6OohaoCDNGVxd9b522SS1-rUM/) by `ItemCategory` (primary) and `ItemId` (secondary)
- Added these as undraftables:
- `gashlai_physiology`
- `quantum_entanglement`
- `muaatagent`
- `nomadagentmercer`
- `creuss_flagship`
- `nekro_mech`
- `blood_pact`
- Added these as optional swaps:
- `ABILITY:dark_whispers`: `PN:blood_pact`
- `ABILITY:the_company`: `AGENT:nomadagentmercer`
- `STARTINGTECH:muaat`: `AGENT:muaatagent`
- Added these as additional components:
- `COMMANDER:creusscommander`: `ABILITY:quantum_entanglement`
- `TECH:lw2`: `ABILITY:mitosis` (was already undraftable)
- `TECH:mr2`: `ABILITY:gashlai_physiology`
- Presumed reasons for extra …
> POK franken errata

- src/main/java/ti4/message/BotLogger.java
Hotfix for #3012 as specified in title.
> hotfix: Default to searching for primary bot-log channel before moving to webhook

- src/main/java/ti4/helpers/Helper.java
- src/main/resources/data/relics/absol.json
- src/main/resources/data/relics/dane_leaks.json
- src/main/resources/data/relics/ds.json
- src/main/resources/data/relics/pok.json
- src/main/resources/data/relics/sigma.json
- src/main/resources/data/technologies/absol.json
- src/main/resources/data/technologies/flagshipping.json
- src/main/resources/data/technologies/pok.json
- src/main/resources/data/units/absol.json
- src/main/resources/data/units/baseUnits.json
- src/main/resources/data/units/ds.json
- src/main/resources/data/units/flagshipping.json
- src/main/resources/data/units/keleres.json
- src/main/resources/data/units/pok.json
Mouse-overs in the webpage version of the game state is failing due to throttling against github, I'm not sure if this is a result of browsers making dozens of requests at the same time or github stopping anonymous retrievals of "hot spot" resources, but moving to a CDN should do the trick in either case.
Statically is a free CDN which handles cache population from github with a pretty minor change in the image retrieval path via the "staticzap" feature (https://statically.io/docs/using-staticzap/) -- Using staticzap you can set the repo owner/name/tag via URL and the images will autopopulate upon first retrieval.  The maps should should be pretty speedy from that point forward.  
Statically/Staticzap uses a 1day TTL on files retrieved from master branches -- so if there's some image you …
> Address image retrieval throttling by using Statically CDN

- src/main/java/ti4/commands/CommandHelper.java
- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/helpers/ButtonHelperAgents.java
- src/main/java/ti4/helpers/ButtonHelperFactionSpecific.java
- src/main/java/ti4/helpers/ButtonHelperTacticalAction.java
- src/main/java/ti4/helpers/FoWHelper.java
- src/main/java/ti4/helpers/SpinRingsHelper.java
- src/main/java/ti4/map/Game.java
- src/main/java/ti4/service/fow/FOWPlusService.java
Having game.getTileByPosition() return a dummy Void tile for positions witthout a tile in FoW Plus mode was a bit risky as that was used so much everywhere. Changed that there's no global "Void" tile, but just ability to activate null tiles.
So added a bunch of null checks too.
> Void tiles from dummy to null

- src/main/java/ti4/commands/custom/CustomizationOptions.java
- src/main/java/ti4/helpers/Constants.java
- src/main/java/ti4/listeners/MessageListener.java
- src/main/java/ti4/map/GameProperties.java
- src/main/java/ti4/map/manage/GameLoadService.java
- src/main/java/ti4/map/manage/GameSaveService.java
- src/main/java/ti4/map/manage/ManagedGame.java
Adds `/custom customization bot_color_reacts:`, which will have the bot react with the colour (destroyer) emoji, in the same vein as faction and strategy card reacts.
> Bot Colour Reacts

- src/main/java/ti4/service/game/CreateGameService.java
- src/main/java/ti4/service/turn/PassService.java
Corrects the chaining of addRolePermissionOverride calls in CreateGameService to ensure overrides are applied sequentially. In PassService, refactors autoProveEndurance logic to break after scoring the 'pe' secret objective, preventing multiple scores in a single pass.
> Fix permission override chaining and SO scoring logic

- src/main/java/ti4/helpers/Storage.java
- src/main/java/ti4/map/persistence/GameSaveService.java
Refactored GameSaveService to write game saves to a temporary file before atomically moving them to the final location, reducing the risk of data corruption. Updated Storage.getGamePath to return absolute, normalized paths. Extracted save logic into helper methods for better clarity and error handling.
> Improve game save reliability with atomic file writes

- src/main/java/ti4/AsyncTI4DiscordBot.java
- src/main/java/ti4/commands/CommandHelper.java
- src/main/java/ti4/commands/admin/AdminCommand.java
- src/main/java/ti4/commands/async/AsyncCommand.java
- src/main/java/ti4/commands/bothelper/BothelperCommand.java
- src/main/java/ti4/commands/bothelper/CorrectFaction.java
- src/main/java/ti4/commands/developer/DeveloperCommand.java
- src/main/java/ti4/commands/developer/RestoreGame.java
- src/main/java/ti4/commands/game/Replace.java
- src/main/java/ti4/commands/game/Swap.java
- src/main/java/ti4/commands/player/PlayerCommand.java
- src/main/java/ti4/map/pojo/SaveMapPojo.java
- src/main/java/ti4/service/game/CreateGameService.java
Replaces manual role checks with CommandHelper.hasRole for consistency and maintainability. Moves CorrectFaction command from player to bothelper, restricts admin commands to admin roles, and moves RestoreGame to developer commands. Updates role collections to use Set instead of List and adds missing roles for Will's server. Cleans up command registration and improves permission logic across commands.
> Refactor role checks and command permissions

- src/main/resources/data/action_cards/acd2.json
- src/main/resources/data/action_cards/legacy_data.json
Moved 'Lazax Cache' and 'Mass Transference' cards from acd2.json to legacy_data.json. Added new 'Cache' and 'Ramming Speed' cards to acd2.json, and updated 'Final Mission' card effect. Restored 'Innovation' card to acd2.json. These changes help maintain accurate and up-to-date action card data, separating legacy and current cards.
> Update and reorganize action card data

- Dockerfile
- pom.xml
- src/main/java/ti4/AsyncTI4DiscordBot.java
- src/main/java/ti4/listeners/BotRuntimeStatsListener.java
- src/main/java/ti4/message/logging/BotLogger.java
- src/main/java/ti4/service/statistics/SREStats.java
- src/main/java/ti4/spring/auth/ErrorLoggingFilter.java
- src/main/java/ti4/spring/configuration/ActuatorApiKeyFilter.java
- src/main/java/ti4/spring/configuration/ManualPrometheusRegistryConfiguration.java
- src/main/java/ti4/spring/configuration/MetricsConfiguration.java
- src/main/java/ti4/spring/configuration/SecurityConfiguration.java
- src/main/resources/config/application.yml
@wholton I have added a fix, but I'm not versed enough with Java to understand the implications. Feedback would be appreciated
The issue was not being able to find a MeterRegistry implementation to inject, which works locally because there's implementations on the classpath, but not in docker (inside a JAR) where the resource files are not merged automatically. The solution should be a migration to a "Spring boot packaging" instead of a regular packaging system, but this seemed like a painful migration. The secondary solution given was to use maven-shade-plugin, which I don't know what to do.
The workaround was to hardwire the class to a prometheus-specific implementation, instead of the implementation-agnostic micrometer is abandoned. This fixes the runtime, but is hardcoded to …
> Add prometheus

- .github/workflows/deploy-to-production.yml
- .github/workflows/restart-bot.yml
- .github/workflows/start-bot.yml
- src/main/java/ti4/AsyncTI4DiscordBot.java
- src/main/java/ti4/commands/user/ShowUserSettings.java
- src/main/java/ti4/image/TileHelper.java
- src/main/java/ti4/website/model/stats/GameStatsDashboardPayload.java
- src/main/java/ti4/website/model/stats/PlayerStatsDashboardPayload.java
Centralized ObjectMapper usage in stats payload classes by using EgressClientManager, reducing redundant instantiations. Improved bot startup logging for clarity, made ShowUserSettings constructor package-private, and updated workflow scripts to use 'set -Eeuo pipefail' for safer shell execution. Also refactored TileHelper to use a single ObjectMapper instance.
> Refactor object mapper usage and improve logging

- src/main/java/ti4/commands/developer/DeveloperCommand.java
- src/main/java/ti4/commands/developer/RunAgainstAllGames.java
- src/main/java/ti4/commands/statistics/ExportToCSV.java
- src/main/java/ti4/migration/DataMigrationManager.java
- src/main/java/ti4/migration/MigrationHelper.java
- src/main/java/ti4/service/statistics/game/GameCountStatisticsService.java
Introduces a new developer command to run custom migration logic across all games, including setting homebrew for 'pi_' factions and renaming 'blaheo' unit holders. Removes the setPiFactionsHomebrew migration from MigrationHelper and DataMigrationManager, consolidating this logic into the new command.
> Add RunAgainstAllGames developer command

- src/main/java/ti4/message/logging/LogBufferManager.java
Replaces manual thread name checks and message routing with ThreadGetter.getThreadInChannel for cleaner and more consistent log message delivery.
> Refactor log message sending to use ThreadGetter

- src/main/java/ti4/commands/developer/RunAgainstAllGames.java
- src/main/java/ti4/commands/statistics/GameStatisticsFilterer.java
- src/main/java/ti4/cron/EndOldGamesCron.java
- src/main/java/ti4/helpers/FoWHelper.java
- src/main/java/ti4/map/Tile.java
- src/main/java/ti4/map/persistence/ManagedGame.java
- src/main/java/ti4/service/game/EndGameService.java
- src/main/java/ti4/service/statistics/MatchmakingRatingService.java
- src/main/java/ti4/service/statistics/game/WinningPathPersistenceService.java
Refactored developer command to set hasEnded and endedDate for games, and improved old game ending logic in EndOldGamesCron. Updated GameStatisticsFilterer to use isNormal filter, excluded alliance games from rating calculations, and improved fog initialization and tile validation. Renamed methods for clarity in WinningPathPersistenceService and EndGameService, and made minor code style improvements.
> Refactor game end handling and update filters

- src/main/java/ti4/map/persistence/GameSaveService.java
- src/main/java/ti4/map/persistence/PosixFileSystemUtility.java
Introduced PosixFileSystemUtility to set file permissions to 0664 on POSIX systems after saving game files. This ensures correct file access rights and improves compatibility with multi-user environments.
> Set POSIX permissions on saved game files

- pom.xml
- src/main/java/ti4/image/ImageHelper.java
- src/main/java/ti4/image/MapGenerator.java
- src/main/java/ti4/service/image/FileUploadService.java
- src/main/java/ti4/website/AsyncTi4WebsiteHelper.java
Replaces JPEG image generation and storage with WebP format for map images. Adds the webp-imageio dependency, implements WebP encoding in ImageHelper, updates MapGenerator and FileUploadService to use WebP, and adjusts file naming and content types accordingly. This change aims to improve image compression and quality.
> Switch map image format from JPG to WebP

- src/main/java/ti4/buttons/handlers/actioncards/ActionCardDeck2ButtonHandler.java
- src/main/resources/data/action_cards/acd2.json
Updated the message and action card text for Ancient Trade Routes to specify that players may transact without being neighbors for the turn, improving clarity and consistency with game rules.
> Clarify Ancient Trade Routes transaction rules

- src/main/java/ti4/buttons/handlers/milty/MiltyDraftButtonHandlers.java
- src/main/java/ti4/commands/game/StartScenario.java
- src/main/java/ti4/commands/milty/StartMilty.java
- src/main/java/ti4/commands/player/Setup.java
- src/main/java/ti4/draft/FrankenDraft.java
- src/main/java/ti4/draft/StandardBagDraft.java
- src/main/java/ti4/draft/items/BlueTileDraftItem.java
- src/main/java/ti4/draft/items/RedTileDraftItem.java
- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/helpers/Helper.java
- src/main/java/ti4/map/Game.java
- src/main/java/ti4/service/draft/DraftSliceHelper.java
- src/main/java/ti4/service/draft/DraftSpec.java
- src/main/java/ti4/service/draft/DraftTileManager.java
- src/main/java/ti4/service/draft/FactionExtraSetupHelper.java
- src/main/java/ti4/service/draft/PlayerSetupService.java
- src/main/java/ti4/service/franken/FrankenDraftBagService.java
- src/main/java/ti4/service/milty/FinishDraftService.java
- src/main/java/ti4/service/milty/GenerateSlicesService.java
- src/main/java/ti4/service/milty/MiltyDraftHelper.java
- src/main/java/ti4/service/milty/MiltyDraftManager.java
- src/main/java/ti4/service/milty/MiltyDraftSpec.java
- src/main/java/ti4/service/milty/MiltyService.java
This PR should have no functional impact, it's just some organizing I thought would be helpful for future changes.
Separates various drafting concepts a bit more cleanly:
- Milty Service: Only for setting up a draft
- Milty Draft Manager: Only for managing an active draft
New files:
- Draft Tile Manager: Handles what tiles could be used to set up a game
- Draft Slice Helper: Utility functions for loading slices
- Faction Extra Setup Service: Faction stuff that drafting needs to integrate with (Keleres)
- Player Setup Service: Actually set up a player
The tile-related "init" methods meant either "add all" or "clear then add all" depending on context, so I've tried to name them more specifically.
> Draft logic split

- src/main/java/ti4/buttons/handlers/actioncards/ActionCardDeck2ButtonHandler.java
- src/main/java/ti4/commands/player/SendCommodities.java
- src/main/java/ti4/map/Player.java
Introduces Player.gainCommodities(int) for incrementing a player's commodities. Updates the Tomb Raiders action card handler to grant 2 commodities to the player. Also refactors some string equality checks in Player.getActiveUnits for consistency. Minor visibility change in SendCommodities constructor.
> Add gainCommodities method and update Tomb Raiders effect

- src/main/java/ti4/helpers/thundersedge/TeHelperDemo.java
- src/main/java/ti4/service/draft/DraftSetupService.java
- src/main/java/ti4/service/draft/DraftSpec.java
- src/main/java/ti4/service/draft/draftables/FactionDraftable.java
- src/main/java/ti4/service/milty/MiltyDraftSpec.java
- src/main/java/ti4/service/milty/MiltyService.java
- Moves the ban list to a single helper, so it only needs to be updated one place
- Adds TE tiles to Nucleus drafting; they get removed by the settings integration
- Remove the **third** DraftSpec class that snuck in when merging in some changes
I hit "Start Draft" w/ 15 factions a bunch of times to make sure I did it right, both for Nucleus and Milty
> Nucleus demo fixes
