AsyncTI4/TI4_map_generator_bot

- src/main/java/ti4/commands/help/HowToMoveUnits.java
add examples to HowToMoveUnits and promote the Modify Units button first and foremost
> Add to /help how_to_move_units

- pom.xml
- src/main/java/ti4/message/BotLogger.java
- src/main/resources/logback.xml
Per: https://jda.wiki/setup/logging/
> Setup Logging

- src/main/java/ti4/buttons/ButtonListener.java
- src/main/java/ti4/commands/cardspn/PNInfo.java
- src/main/java/ti4/commands/special/CombatRoll.java
- src/main/java/ti4/helpers/CombatModHelper.java
- src/main/java/ti4/model/CombatModifierModel.java
- src/main/resources/data/combat_modifiers/combat_modifiers.json
- tekklar was getting added to combat mods when being sent to another player, rather than when being played
- bunker is now included & close quarters fixed with a new 'applyToOpponent field
> Tekklar fix & added applyToOpponent

- src/main/java/ti4/commands/tech/TechButton.java
- src/main/java/ti4/commands/tech/TechCommand.java
- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/helpers/ButtonHelperAbilities.java
- src/main/java/ti4/helpers/ButtonHelperActionCards.java
- src/main/java/ti4/helpers/ButtonHelperFactionSpecific.java
- src/main/java/ti4/helpers/Helper.java
- src/main/java/ti4/model/TechnologyModel.java
make getTech buttons handle homebrew properly
> Homebrew Tech Buttons

- src/main/java/ti4/buttons/ButtonListener.java
- src/main/java/ti4/commands/cardsac/PlayAC.java
- src/main/java/ti4/commands/cardspn/PlayPN.java
- src/main/java/ti4/commands/combat/CombatCommand.java
- src/main/java/ti4/commands/combat/CombatRoll.java
- src/main/java/ti4/commands/leaders/ExhaustLeader.java
- src/main/java/ti4/commands/leaders/HeroPlay.java
- src/main/java/ti4/commands/special/SpecialCommand.java
- src/main/java/ti4/commands/tech/TechExhaust.java
- src/main/java/ti4/generator/Mapper.java
- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/helpers/CombatHelper.java
- src/main/java/ti4/helpers/CombatMessageHelper.java
- src/main/java/ti4/helpers/CombatModHelper.java
- src/main/java/ti4/helpers/CombatTempModHelper.java
- src/test/java/ti4/helpers/CombatModHelperTest.java
tidy up
- created separate classes for tempmod and messages
- changed roll to use DiceHelper
- removed old code
> Combat roll refactor

- src/main/resources/data/relics/codexii.json
- src/main/resources/data/relics/pok.json
> Add flavor text for PoK, Codex II relics

- src/main/java/ti4/DataMigrationManager.java
- src/main/java/ti4/generator/MapGenerator.java
- and account for naalu and multiple SCs
> Make crossed out SCs slightly prettier

- src/main/java/ti4/buttons/ButtonListener.java
Reverts AsyncTI4/TI4_map_generator_bot#1450
> Revert "Fin new branch"

- src/main/java/ti4/buttons/ButtonListener.java
- src/main/java/ti4/commands/bothelper/JazzCommand.java
- src/main/java/ti4/commands/combat/CombatRoll.java
- src/main/java/ti4/commands/player/Setup.java
- src/main/java/ti4/commands/statistics/GameStats.java
- src/main/java/ti4/commands/status/ListTurnOrder.java
- src/main/java/ti4/helpers/AgendaHelper.java
- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/helpers/ButtonHelperAgents.java
- src/main/java/ti4/helpers/ButtonHelperHeroes.java
- src/main/java/ti4/helpers/ButtonHelperModifyUnits.java
- src/main/java/ti4/helpers/FoWHelper.java
- src/main/java/ti4/helpers/Helper.java
- src/main/java/ti4/model/AgendaModel.java
- src/test/java/ti4/draft/FrankenItemTest.java
I ran IntelliJ silent cleanup and then committed the things that looked like reasonable changes.
I also did some refactoring of my own
> More code cleanup

- src/main/java/ti4/buttons/ButtonListener.java
- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/helpers/ButtonHelperModifyUnits.java
When the ghoti player uses sling relay systems with their mechs should now show up as available
I started on refactoring ButtonListener. There is more to come.
> Partial ghoti mech functionality and refactoring

- src/main/resources/data/leaders/pok.json
> Update Field Marshal Mercer 

- src/main/resources/data/promissory_notes/absol.json
I just saw this issue, was bored and took the liberty to open this PR. Fixes #1209 
Unfortunately I don't have an environment for java, so I did not have chance to test. But I assumed that adding missing colors to the data files would get the job done.
> Add absol's PS for missing colors (Fixes #1209)

- src/main/resources/data/factions/project_pi.json
Hopefully a correct update to the Pi Factions with RealHomebreID
> Jl beck13 patch 1

- src/main/java/ti4/commands/bothelper/CreateGameChannels.java
- src/main/java/ti4/helpers/GlobalSettings.java
- src/test/java/ti4/commands/bothelper/CreateGameChannelsTest.java
default 10 games per category unless GlobalSetting is set
> Dynamic NewGame Category Size

- src/main/java/ti4/commands/custom/CustomizationOptions.java
- src/main/java/ti4/helpers/AliasHandler.java
- src/main/java/ti4/helpers/Constants.java
- src/main/java/ti4/map/Game.java
- src/main/java/ti4/map/GameSaveLoadManager.java
- src/main/java/ti4/message/MessageHelper.java
- src/main/resources/alias/rules_injection.properties
> add rules injection stub

- src/main/java/ti4/generator/TileHelper.java
only a partial commit of the previous one with performance issues
> Duplicate Draft Tiles

- src/main/java/ti4/commands/milty/MiltyDraftHelper.java
- src/main/java/ti4/commands/milty/MiltyDraftManager.java
- src/main/java/ti4/commands/milty/StartMilty.java
- src/main/java/ti4/commands/player/TurnEnd.java
- src/main/java/ti4/generator/MapGenerator.java
- src/main/java/ti4/helpers/MapTemplateHelper.java
- src/main/java/ti4/message/MessageHelper.java
- src/main/java/ti4/model/PlanetModel.java
- make file upload not awful
- refactor image creation some
- get rid of action channel map butts
- change draft summary layout
- fix a couple bugs
- fix value verification code
> Update milty draft

- src/main/java/ti4/commands/milty/MiltyDraftHelper.java
- src/main/java/ti4/commands/milty/StartMilty.java
- and other milty draft visualization updates
> Fog Picked Slices

- src/main/java/ti4/buttons/ButtonListener.java
- src/main/java/ti4/commands/bothelper/JazzCommand.java
- src/main/java/ti4/commands/bothelper/Observer.java
- src/main/java/ti4/commands/milty/MiltyDraftHelper.java
- src/main/java/ti4/commands/milty/MiltyDraftManager.java
- src/main/java/ti4/commands/player/ChangeColor.java
- src/main/java/ti4/commands/player/SCPick.java
- src/main/java/ti4/commands/player/Stats.java
- src/main/java/ti4/draft/FrankenDraft.java
- src/main/java/ti4/helpers/Helper.java
- src/main/java/ti4/helpers/MapTemplateHelper.java
- src/main/java/ti4/map/GameSaveLoadManager.java
- src/main/java/ti4/model/MapTemplateModel.java
- src/main/resources/data/map_templates/12pTispoon.json
- src/main/resources/data/map_templates/9pLuminous.json
- src/main/resources/data/map_templates/standardMiltyLayouts.json
- Milty draft adds custodes now
- milty draft handles DS tiles better
- franken draft handles DS tiles better
- bothelper observer remove does correct things to permissions
- fix change color bug with control markers
> Fix a few bugs

- src/main/java/ti4/commands/bothelper/JazzCommand.java
- src/main/java/ti4/commands/milty/StartMilty.java
- src/main/java/ti4/helpers/Constants.java
- src/main/java/ti4/helpers/Emojis.java
- src/main/java/ti4/helpers/ImageHelper.java
- src/main/java/ti4/helpers/MapTemplateHelper.java
- Also make loading url images as a square center the imageinstead of stretching it
> Fix the custodian token in milty draft properly

- src/main/java/ti4/commands/milty/StartMilty.java
- src/main/java/ti4/helpers/Helper.java
> Dont integer overflow checking milty draft elapsed time

- src/main/java/ti4/message/BotLogger.java
- src/main/java/ti4/message/MessageHelper.java
max 9 instead of 10 embeds per message
improved rest failure logging
> fix large embed messages

- src/main/java/ti4/draft/DraftItem.java
- src/main/java/ti4/draft/items/AbilityDraftItem.java
- src/main/java/ti4/draft/items/AgentDraftItem.java
- src/main/java/ti4/draft/items/CommanderDraftItem.java
- src/main/java/ti4/draft/items/CommoditiesDraftItem.java
- src/main/java/ti4/draft/items/FlagshipDraftItem.java
- src/main/java/ti4/draft/items/HeroDraftItem.java
- src/main/java/ti4/draft/items/HomeSystemDraftItem.java
- src/main/java/ti4/draft/items/MechDraftItem.java
- src/main/java/ti4/draft/items/PNDraftItem.java
- src/main/java/ti4/draft/items/StartingFleetDraftItem.java
- src/main/java/ti4/draft/items/StartingTechDraftItem.java
- src/main/java/ti4/draft/items/TechDraftItem.java
- src/main/java/ti4/helpers/Helper.java
- src/main/java/ti4/model/DraftErrataModel.java
- src/main/resources/data/abilities/ds.json
- src/main/resources/data/factions/ds.json
- src/main/resources/data/franken_errata/ds.json
- src/main/resources/data/franken_errata/pok.json
- src/test/java/ti4/draft/FrankenItemTest.java
- src/test/java/ti4/model/DraftErrataModelTest.java
not all, but some, of Luminous' undraftables
Added tests to validate franken errata item IDs
> Franken Errata updates

- src/main/resources/data/leaders/pok.json
Real simple one I noticed today in a game.
> Fix for typo in Jol-Nar Hero

- src/main/java/ti4/MessageListener.java
- src/main/java/ti4/commands/fow/Whisper.java
- Notify sender if target player was not found, rather than sending the message to yourself as currently happens.
- Check in FoW is target player is a neighbour and notify if not.
> Checks to tocolor messages

- src/main/java/ti4/generator/MapGenerator.java
If faction was null and it got saved, it comes back as "null". Check for that too.
> Added 'null' check to faction text

- src/main/java/ti4/UserJoinServerListener.java
- src/main/java/ti4/buttons/ButtonListener.java
- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/helpers/Constants.java
- src/main/java/ti4/helpers/StringHelper.java
- src/main/java/ti4/helpers/async/RoundSummaryHelper.java
- src/main/java/ti4/listeners/ModalListener.java
- src/main/java/ti4/listeners/annotations/AnnotationHandler.java
- src/main/java/ti4/listeners/annotations/NamedParam.java
- src/main/java/ti4/listeners/annotations/SelectionHandler.java
- src/main/java/ti4/listeners/context/SelectionMenuContext.java
- src/main/java/ti4/map/Player.java
- src/main/java/ti4/selections/SelectionMenuProvider.java
- annotation driven handlers now accept a wide range of parameters
- - event, game, player, componentID
- fix null choose to vote
> Make annotation driven handlers more generic

- src/main/java/ti4/AsyncTI4DiscordBot.java
- src/main/java/ti4/commands/milty/DebugMilty.java
- src/main/java/ti4/helpers/settingsFramework/menus/SettingsMenu.java
- src/main/java/ti4/listeners/SelectionMenuListener.java
- src/main/java/ti4/listeners/context/ModalContext.java
- src/main/java/ti4/listeners/context/SelectionMenuContext.java
- src/main/java/ti4/map/Game.java
- src/main/java/ti4/map/GameSaveLoadManager.java
- src/main/java/ti4/map/Player.java
- Don't save games that haven't been touched since before the bot reloaded
- Don't save game JSON in production. It is very slow.
- Defer loading the milty draft settings until the game requests it
> Save fewer games when the bot reboots

- src/main/java/ti4/buttons/Buttons.java
- src/main/java/ti4/commands/uncategorized/CardsInfo.java
- src/main/java/ti4/helpers/Constants.java
- src/main/java/ti4/helpers/StringHelper.java
- src/main/java/ti4/helpers/async/NotepadHelper.java
- src/main/java/ti4/map/GameSaveLoadManager.java
- src/main/java/ti4/map/Player.java
- Move cards info refresh to the end of the list
> Add a notepad in cards info

- src/main/java/ti4/AsyncTI4DiscordBot.java
- src/main/java/ti4/helpers/Storage.java
- src/main/java/ti4/map/GameManager.java
- src/main/java/ti4/map/GameSaveLoadManager.java
This reverts commit 67b0d5270263b788355664f9186800438e994cba.
> Revert "parallel-load (#1894)"

- src/main/java/ti4/AsyncTI4DiscordBot.java
- src/main/java/ti4/map/GameManager.java
- src/main/java/ti4/map/GameSaveLoadManager.java
This reverts commit 14011f8337685b3c3d90aa75b1702ab73c318ce7.
> Revert "cleanup (#1907)"

- src/main/java/ti4/map/GameManager.java
- src/main/java/ti4/map/GameSaveLoadManager.java
This reverts commit b7415fc881cf551737ca9b605da7c3d2b0cfdb08.
> Revert "Parallel load 2 (#1912)"

- src/main/java/ti4/helpers/AgendaHelper.java
Posts a message in #disaster-watch-party whenever somebody loses 12+TGs to Economic Equality.
> Economic Equality message in #disaster-watch-party for a big TG loss.

- src/main/java/ti4/commands/tech/TechExhaust.java
- src/main/java/ti4/generator/MapGenerator.java
- src/main/java/ti4/helpers/ButtonHelperFactionSpecific.java
> Show Unused Creuss Wormhole Tokens In Creuss Player Area

- src/main/java/ti4/buttons/ButtonListener.java
- src/main/java/ti4/commands/status/RevealStage1.java
- src/main/java/ti4/commands/status/RevealStage2.java
- src/main/java/ti4/helpers/ButtonHelper.java
Added a space between game ping and Status Cleanup title and made the title bold
Added more reminder to click ready in FoW, since it's forgotten so often and game hangs untill GM reminds them!
> Status homework

- src/main/java/ti4/autocomplete/AutoCompleteProvider.java
- src/main/java/ti4/buttons/ButtonListener.java
- src/main/java/ti4/commands/uncategorized/CardsInfo.java
- src/main/java/ti4/commands/uncategorized/ShowGame.java
- src/main/java/ti4/generator/MapGenerator.java
- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/helpers/DisplayType.java
Adds a shipless display, and allows all the map features to be accessed with buttons.
> Update Map Features

- src/main/java/ti4/autocomplete/AutoCompleteProvider.java
- src/main/java/ti4/generator/MapGenerator.java
- src/main/java/ti4/helpers/DisplayType.java
`/show_game display_type: landscape` will create a landscape map, with the map on the left and the stats on the right. Implements #24 .
> Add landscape map option

- src/main/java/ti4/buttons/ButtonListener.java
- src/main/java/ti4/commands/special/MoveAllUnits.java
Added option to use CC for /special move_all_units
> Move all units with cc

- src/main/java/ti4/commands/bothelper/CreateFOWGameChannels.java
> Remove game name from fow create options

- src/main/java/ti4/buttons/ButtonListener.java
- src/main/java/ti4/helpers/Helper.java
When a FoW game ends, give the option to bestow titles.
> Option to give titles in FoW

- src/main/java/ti4/helpers/Emojis.java
- src/main/resources/data/color.properties
- src/main/resources/data/colors/gradientColors.json
> Eronous patch 9

- src/main/java/ti4/generator/MapGenerator.java
Bumps SOs down away from SC Follows and Neighbour list. With 4+ SOs, tightens border.
> Slight adjustments to SO positioning in PA

- src/main/resources/data/franken_errata/ds.json
Per: https://discord.com/channels/943410040369479690/1164480904148824074/1286808921792843890
> Franken Disable Abyssal Embrace

- src/main/java/ti4/commands/milty/MiltyDraftHelper.java
- src/main/java/ti4/generator/MapGenerator.java
- src/main/java/ti4/helpers/ImageHelper.java
- src/main/java/ti4/helpers/WebHelper.java
This reverts commit 329a74bce40b382dc215cc8863d2b93bfc54ee12.
> Revert "webp-2 (#2202)"

- src/main/java/ti4/commands/custom/CustomCommand.java
- src/main/java/ti4/commands/custom/PeekAtObjectiveDeck.java
- src/main/java/ti4/commands/custom/PeekAtStage1.java
- src/main/java/ti4/commands/custom/PeekAtStage2.java
- src/main/java/ti4/commands/player/SCPlay.java
- src/main/java/ti4/helpers/ButtonHelperAbilities.java
- src/main/java/ti4/helpers/Constants.java
- src/main/resources/data/strategy_card_sets/unfulvio.json
- src/main/resources/data/strategy_cards/unfulvio.json
https://www.reddit.com/r/twilightimperium/comments/vlo75i/intrigue_9th_strategy_card_revised
> add Unfulvio's Intrigue SC

- src/main/java/ti4/buttons/UnfiledButtonHandlers.java
- src/main/java/ti4/commands/planet/PlanetExhaustAbility.java
- src/main/java/ti4/helpers/ButtonHelperAgents.java
- src/main/java/ti4/message/MessageHelper.java
Reverts AsyncTI4/TI4_map_generator_bot#2305
> Revert "Fix null embeds"

- src/main/java/ti4/commands/planet/PlanetAdd.java
Not sure I got the emoji name right
> Change emoji on custodians message

- src/main/java/ti4/image/MapGenerator.java
Also prevents promissory information greying out when in FoW mode.
> Brings back reinfocement unit images for non-decaled players

- src/main/java/ti4/AsyncTI4DiscordBot.java
- src/main/java/ti4/listeners/AutoCompleteListener.java
- src/main/java/ti4/listeners/MessageListener.java
- src/main/java/ti4/listeners/ModalListener.java
- src/main/java/ti4/listeners/SelectionMenuListener.java
- src/main/java/ti4/listeners/SlashCommandListener.java
- src/main/java/ti4/listeners/UserJoinServerListener.java
This reverts commit 60aff6a42d2eeac440ebd640fc36ed451e65bbb6.
> Revert "add-executors (#2453)"

- src/main/java/ti4/map/GameSaveLoadManager.java
This reverts commit 51fbf14474319b00c7a0fb4f3c826fbd2badce24.
> Revert "try to delete old undo files upon load"

- CONTRIBUTING.md
Adds prerequisite setup steps to documentation. Defaults to vscode, but can add setup for other IDEs in the future.
> Update contribution documentation to be more comprehensive

- src/main/java/ti4/AsyncTI4DiscordBot.java
- src/main/java/ti4/listeners/annotations/AnnotationHandler.java
- src/main/java/ti4/map/Game.java
- src/main/java/ti4/map/GameSaveLoadManager.java
- src/main/java/ti4/service/milty/MiltyDraftHelper.java
- src/main/java/ti4/service/milty/MiltyDraftManager.java
This reverts commit 789a88a6ed372497ac04466f27aa2853884fe151.
> Revert "Speedup (#2496)"

- src/main/java/ti4/AsyncTI4DiscordBot.java
- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/helpers/ButtonHelperActionCards.java
- src/main/java/ti4/image/TileGenerator.java
- src/main/java/ti4/listeners/annotations/AnnotationHandler.java
- src/main/java/ti4/map/Game.java
- src/main/java/ti4/map/GameSaveLoadManager.java
- src/main/java/ti4/service/milty/MiltyDraftHelper.java
- src/main/java/ti4/service/milty/MiltyDraftManager.java
This reverts commit 1963a539bfc525999e6bd8c14c4b4421e0017df6.
> Revert "Reapply speedup (#2498)"

- src/main/java/ti4/AsyncTI4DiscordBot.java
This reverts commit f35fa2b5f5c0afe28a3e2d0f350ba407053d7de6.
> Revert "Update AsyncTI4DiscordBot.java (#2514)"

- pom.xml
- src/main/java/ti4/commands2/help/SampleColors.java
- src/main/java/ti4/commands2/help/SampleDecals.java
- src/main/java/ti4/helpers/WebHelper.java
- src/main/java/ti4/helpers/async/JimboImageHelper.java
- src/main/java/ti4/image/BannerGenerator.java
- src/main/java/ti4/image/ImageHelper.java
- src/main/java/ti4/image/MapGenerator.java
- src/main/java/ti4/image/TileGenerator.java
- src/main/java/ti4/service/game/CreateGameService.java
- src/main/java/ti4/service/image/FileUploadService.java
- src/main/java/ti4/service/milty/MiltyDraftHelper.java
This reverts commit b79cc89c1b8e79905f179d48fcc2a7e85bec5394.
> Revert "webp retry (#2560)"

- pom.xml
- src/main/java/ti4/commands2/help/SampleColors.java
- src/main/java/ti4/commands2/help/SampleDecals.java
- src/main/java/ti4/helpers/WebHelper.java
- src/main/java/ti4/helpers/async/JimboImageHelper.java
- src/main/java/ti4/image/BannerGenerator.java
- src/main/java/ti4/image/ImageHelper.java
- src/main/java/ti4/image/MapGenerator.java
- src/main/java/ti4/image/TileGenerator.java
- src/main/java/ti4/service/game/CreateGameService.java
- src/main/java/ti4/service/image/FileUploadService.java
- src/main/java/ti4/service/milty/MiltyDraftHelper.java
This reverts commit 27ee103ce244cbbbee2d9b87c2c3d755718dadba.
> Revert "Reapply webp again (#2563)"

- src/main/java/ti4/buttons/handlers/game/CreateGameButtonHandler.java
- src/main/java/ti4/buttons/handlers/game/RematchButtonHandler.java
- src/main/java/ti4/commands2/player/SCPlay.java
- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/helpers/ThreadArchiveHelper.java
- src/main/java/ti4/helpers/ThreadHelper.java
- src/main/java/ti4/listeners/AutoCompleteListener.java
- src/main/java/ti4/listeners/ButtonListener.java
- src/main/java/ti4/listeners/MessageListener.java
- src/main/java/ti4/listeners/ModalListener.java
- src/main/java/ti4/listeners/SelectionMenuListener.java
- src/main/java/ti4/listeners/SlashCommandListener.java
- src/main/java/ti4/listeners/UserJoinServerListener.java
- src/main/java/ti4/listeners/UserLeaveServerListener.java
- src/main/java/ti4/listeners/context/ButtonContext.java
- src/main/java/ti4/message/BotLogger.java
- src/main/java/ti4/message/MessageHelper.java
- src/main/java/ti4/processors/ButtonProcessor.java
- src/main/java/ti4/selections/SelectionMenuProcessor.java
- src/main/java/ti4/service/combat/StartCombatService.java
- src/main/java/ti4/service/game/CreateGameService.java
- src/main/java/ti4/service/game/EndGameService.java
- src/main/java/ti4/service/strategycard/PlayStrategyCardService.java
This reverts commit a35816f373aff06a5ef66f130354fef74de7ffb0.
> Revert "Fix race condition and button context (#2597)"

- src/main/java/ti4/helpers/ButtonHelper.java
> Filter out spacedocks for assault cannon combat

- src/main/java/ti4/commands2/map/AddBorderAnomaly.java
- src/main/java/ti4/commands2/map/RemoveBorderAnomaly.java
> Improve BorderAnomaly commands

- src/main/java/ti4/autocomplete/AutoCompleteProvider.java
- src/main/java/ti4/commands2/map/AddTileListRandom.java
- src/main/java/ti4/commands2/map/AddTileRandom.java
- src/main/java/ti4/commands2/map/MapCommand.java
- src/main/java/ti4/helpers/Constants.java
- src/main/java/ti4/service/map/AddTileListService.java
- src/main/resources/systems/er66.json
> AddTileListRandom command

- src/main/java/ti4/commands2/custom/CustomCommand.java
- src/main/java/ti4/commands2/user/OfferAFKTimeOptions.java
- src/main/java/ti4/commands2/user/UserCommand.java
> Moved afk setting to user command [skip ci]

- src/main/java/ti4/commands2/fow/CheckChannels.java
- src/main/java/ti4/commands2/game/Replace.java
- src/main/java/ti4/helpers/Helper.java
> Update FoW channel permissions

- src/main/java/ti4/buttons/UnfiledButtonHandlers.java
- src/main/java/ti4/commands2/fow/FOWCommand.java
- src/main/java/ti4/commands2/fow/PrivateCommunicationsCheck.java
- src/main/java/ti4/helpers/Constants.java
- src/main/java/ti4/service/fow/FowCommunicationThreadService.java
- src/main/java/ti4/service/game/StartPhaseService.java
> Fow improvements

- src/main/java/ti4/commands2/fow/PingActivePlayer.java
Because BLT wants to annoy someone.
> No time limit for GMs

- CONTRIBUTING.md
Clarified major steps for adding the bot in the dev's discord server; Added paragraph for forking+cloning.
> [#2662]: Added instructions for running the bot locally in the terminal

- src/main/java/ti4/map/manage/GameLoadService.java
- src/main/java/ti4/map/manage/GameSaveService.java
This reverts commit 3ab4a563d7d8f5bff5802d38aa264046d4a96da6.
> Revert "Add file locking to save/load (#2752)"

- src/main/java/ti4/commands/admin/AdminCommand.java
- src/main/java/ti4/commands/admin/ReloadGame.java
> reloadgame command

- src/main/java/ti4/commands/map/PreviewMapTemplate.java
- src/main/java/ti4/helpers/MapTemplateHelper.java
- src/main/java/ti4/helpers/settingsFramework/menus/GameSettings.java
- Automatically preview the new template when you edit it in milty settings
> Fix a couple bugs with Preview Map Template

- src/main/java/ti4/buttons/UnfiledButtonHandlers.java
- src/main/java/ti4/commands/game/Info.java
- src/main/java/ti4/commands/user/SetPreferredColourList.java
- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/image/Mapper.java
- src/main/java/ti4/map/Player.java
- src/main/java/ti4/map/manage/GameLoadService.java
- src/main/java/ti4/migration/DataMigrationManager.java
- src/main/java/ti4/migration/MigrationHelper.java
- src/main/java/ti4/service/game/StartPhaseService.java
- src/main/java/ti4/settings/users/UserSettings.java
> Misc Fixes

- src/main/java/ti4/buttons/UnfiledButtonHandlers.java
- src/main/java/ti4/commands/player/Pass.java
- src/main/java/ti4/service/turn/PassService.java
- src/main/java/ti4/service/turn/StartTurnService.java
> dedupe passing methods (#2843)

- src/main/resources/data/factions/base.json
- src/main/resources/data/factions/ds.json
> Added DS Faction Sheet Images & Links #2484

- src/main/resources/data/technologies/absol.json
Correcting text as described in this thread: https://discord.com/channels/943410040369479690/1009507056606249020/1340116430909210736
> Updating Magen

- src/main/java/ti4/buttons/Buttons.java
- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/helpers/WebHelper.java
- src/main/java/ti4/image/MapGenerator.java
- src/main/java/ti4/service/ShowGameService.java
- src/main/java/ti4/service/image/FileUploadService.java
- We can trigger this in prod by simply turning off sending data to the website
>  Use an "Open in Browser" button locally

- src/main/resources/data/franken_errata/ds.json
- Added the Ghoti home system to the spawning grounds ability as and additional component
- Added branch offices 2-4 to corporate entity as additional components
> Fixed a few places that disagreed with the luminous csv

- src/main/java/ti4/message/BotLogger.java
> hotfix: Stop pinging users in log messages

- src/main/resources/data/abilities/ds.json
I noticed I got obsessive designs twice in my franken game but actually one of them was prescience
> Fixing copy-paste error adding Prescience

- src/main/java/ti4/cron/UploadStatsCron.java
- src/main/java/ti4/helpers/WebHelper.java
- src/main/resources/data/action_cards/acd2.json
This reverts commit 16e4aa9a8f23f068acfe14b42b25d14cc6f004a0.
> Revert "Statistics upload fix (#3065)"

- src/main/java/ti4/AsyncTI4DiscordBot.java
- src/main/java/ti4/buttons/UnfiledButtonHandlers.java
- src/main/java/ti4/commands/search/SearchSources.java
- src/main/java/ti4/helpers/AliasHandler.java
- src/main/java/ti4/helpers/DisplayType.java
- src/main/java/ti4/image/MapGenerator.java
- src/main/java/ti4/image/Mapper.java
- src/main/java/ti4/image/TileGenerator.java
- src/main/java/ti4/image/UnitRenderGenerator.java
- src/main/java/ti4/map/Game.java
- src/main/java/ti4/map/GameProperties.java
- src/main/java/ti4/processors/ButtonProcessor.java
- src/main/java/ti4/service/ShowGameService.java
- src/main/resources/data/sources/sources.json
Added DisplayType Unlocked
Few comments added and instructions reordered
Slight improvments to /search sources
> Tsi 1 displayType unlocked

- src/main/java/ti4/autocomplete/AutoCompleteProvider.java
- src/main/java/ti4/commands/search/SearchSources.java
- src/main/java/ti4/helpers/DisplayType.java
- src/main/java/ti4/helpers/RegexHelper.java
- src/main/java/ti4/image/Mapper.java
- src/main/java/ti4/model/Source.java
- src/main/java/ti4/model/SourceModel.java
- src/main/resources/data/sources/sources.json
- src/test/java/ti4/model/TokenModelTest.java
> more on search sources

- src/main/java/ti4/commands/search/SearchSources.java
- src/main/java/ti4/model/Source.java
- src/main/java/ti4/model/SourceModel.java
- src/main/resources/data/explores/uncharted_space.json
Fixing /search sources check_sources
Adding entries to sources.json
More comments
> Sources and search sources command

- src/main/resources/data/franken_errata/ds.json
- src/main/resources/data/franken_errata/pok.json
Correct some components' draftable status in Franken.
> Correct some components' draftable status in Franken and add alternate texts

- src/main/java/ti4/autocomplete/AutoCompleteProvider.java
- src/main/java/ti4/commands/custom/CustomizationOptions.java
- src/main/java/ti4/commands/search/SearchAttachmentsSubcommand.java
- src/main/java/ti4/commands/search/SearchCommand.java
- src/main/java/ti4/commands/search/SearchSources.java
- src/main/java/ti4/commands/search/SearchTokensSubcommand.java
- src/main/java/ti4/commands/statistics/GameStatisticsFilterer.java
- src/main/java/ti4/draft/DraftItem.java
- src/main/java/ti4/draft/FrankenDraft.java
- src/main/java/ti4/draft/StandardBagDraft.java
- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/helpers/Constants.java
- src/main/java/ti4/helpers/RegexHelper.java
- src/main/java/ti4/helpers/settingsFramework/menus/PlayerFactionSettings.java
- src/main/java/ti4/image/Mapper.java
- src/main/java/ti4/model/AttachmentModel.java
- src/main/java/ti4/model/TokenModel.java
- src/main/java/ti4/selections/selectmenus/SelectFaction.java
- src/main/java/ti4/service/milty/MiltyService.java
- src/main/java/ti4/service/statistics/GameWinsWithOtherFactionsService.java
- src/main/java/ti4/service/statistics/game/FactionWinPercentStatisticsService.java
- src/main/resources/data/abilities/ds.json
- src/main/resources/data/relics/codexii.json
- src/main/resources/data/technologies/ds.json
- src/main/resources/data/tokens/other.json
- src/test/java/ti4/model/FactionModelTest.java
- src/test/java/ti4/model/TokenModelTest.java
organised Mapper + refactoring of some function
migrated /search sources get...Sources() functions to Mapper
added /search tokens and /search attachments
modified TokenModel and AttachmentModel
organised search values in Constants
also a few fix to data
> Tsi 1: 3rd attempt... Mapper cleaning + 2 new commands /search

- src/main/java/ti4/helpers/ButtonHelper.java
- src/main/java/ti4/service/tactical/TacticalActionService.java
and put end of turn button back
> Don't delete movement summary after tactics action

- src/main/java/ti4/helpers/ButtonHelperActionCards.java
Would love someone to actually check this before pushing, but it should just be a quick typo fix.
> Fix typo in salvage AC  resolution text

- src/main/resources/data/franken_errata/ds.json
Minor update to Nivyn hero to be "optional" to the Mech, not "added".
> Minor update to Nivyn hero in Franken

- src/main/resources/data/action_cards/acd2.json
Made it action phase instead of agenda phase
> Update Virulent Payload

- src/main/java/ti4/commands/user/WipeTurnTime.java
- src/main/java/ti4/helpers/ButtonHelperHeroes.java
- src/main/java/ti4/helpers/Units.java
This reverts commit bad4f6ea81c06dd36ae879e53de5a5e709453c7e.
> Revert "Refactor locking and thread safety in game utilities (#3432)"

- src/main/java/ti4/website/AsyncTi4WebsiteHelper.java
- *** Add some logging for bot requests**
- *** DIfferent debug logging to isolate the error**
> Added some more troubleshooting code to the bot.

- src/main/java/ti4/website/AsyncTi4WebsiteHelper.java
- *** Add some logging for bot requests**
- *** DIfferent debug logging to isolate the error**
- *** More Exception Logging**
> Still trying to track down the new error

- src/main/java/ti4/autocomplete/AutoCompleteProvider.java
- src/main/java/ti4/buttons/handlers/agenda/resolver/AbsolConstitutionAgendaResolver.java
- src/main/java/ti4/commands/game/StartScenario.java
- src/main/java/ti4/commands/status/ListDiceLuck.java
- src/main/java/ti4/service/game/StartPhaseService.java
- src/main/resources/config/application.yml
Replaced several usages of ArrayList with the more general List interface for improved code flexibility and readability. Refactored a switch statement in StartScenario to use the enhanced switch expression. Removed a commented debug line from AutoCompleteProvider. Added a new application.yml configuration file to set the server port to 8081.
> Refactor collections and add application config

- src/main/java/ti4/spring/service/auth/DiscordOpaqueTokenIntrospector.java
- **Adding logging to the discord token checking.**
- *** THank you spotless**
- *** I hope it's this**
> Trying to fix the Discord auth

- src/main/java/ti4/spring/service/auth/DiscordOpaqueTokenIntrospector.java
Refactored DiscordOpaqueTokenIntrospector to extract authentication logic into separate methods for clarity and maintainability. Updated the Discord API endpoint to use v10 and improved error handling and logging for failed authentication attempts.
> Refactor Discord token introspection logic

- src/main/java/ti4/commands/user/WipeTurnTime.java
- src/main/java/ti4/spring/service/auth/CircuitBreakerFilter.java
Added a readiness check for AsyncTI4DiscordBot in CircuitBreakerFilter to improve service availability handling. Refactored WipeTurnTime to remove redundant event parameter and message sending, streamlining the wipe logic.
> Enhance circuit breaker and refactor WipeTurnTime

- src/main/java/ti4/message/logging/LogBufferManager.java
Wrapped the log buffer draining and message sending logic in try-catch blocks to improve robustness and log errors when exceptions occur. Refactored event log handling into a separate method for clarity.
> Add error handling to log buffer draining and sending

- pom.xml
- src/main/java/ti4/AsyncTI4DiscordBot.java
- src/main/java/ti4/listeners/BotRuntimeStatsListener.java
- src/main/java/ti4/message/logging/BotLogger.java
- src/main/java/ti4/service/statistics/SREStats.java
- src/main/java/ti4/spring/auth/ErrorLoggingFilter.java
- src/main/java/ti4/spring/configuration/ActuatorApiKeyFilter.java
- src/main/java/ti4/spring/configuration/MetricsConfiguration.java
- src/main/java/ti4/spring/configuration/SecurityConfiguration.java
- src/main/resources/config/application.yml
Integrate Spring Boot Actuator and Micrometer Prometheus for runtime monitoring. Add BotRuntimeStatsListener and SREStats to track error logs and bot statistics. Secure actuator (/actuator/prometheus) endpoints with API key filter. Update dependencies and configuration for metrics support.
> Add runtime stats, Prometheus metrics, and actuator endpoints

- pom.xml
- src/main/java/ti4/AsyncTI4DiscordBot.java
- src/main/java/ti4/image/DrawingUtil.java
- src/main/java/ti4/image/Mapper.java
- src/main/java/ti4/map/Player.java
- src/main/java/ti4/map/UnitHolder.java
- src/main/java/ti4/model/ColorModel.java
- src/test/java/ti4/testUtils/BaseTi4Test.java
- src/test/java/ti4/testUtils/JsonValidator.java
Refactored ColorModel to use getPrimaryColor/getSecondaryColor methods and updated all usages accordingly. Improved color deserialization in Mapper with a custom deserializer for multiple color formats. Cleaned up UnitHolder logic and removed unused methods. Updated pom.xml to remove unused dependencies and plugins, switching to Spring Boot Actuator and Prometheus for monitoring. Minor test and formatting improvements.
> Refactor color handling and update dependencies

- src/main/java/ti4/migration/DataMigrationManager.java
- src/main/java/ti4/migration/MigrationHelper.java
- src/main/resources/systems/d17.json
This reverts commit 50297a5d30229e35faf3b512cb3a5c11d358e771.
> Revert "Fix Biaheo unit holder name (#3571)"

- .github/workflows/restart-bot.yml
- .github/workflows/start-bot.yml
- .github/workflows/stop-bot.yml
Removed redundant scheduled_upload.sh calls and added 'set -eu' for safer script execution in restart-bot.yml and stop-bot.yml. Minor formatting improvements were made for consistency across all bot workflow scripts.
> Refactor bot workflow scripts for consistency

- .github/workflows/force-backup-of-savefiles.yml
This reverts commit bf2a7c46c4026ffe473012c9295a598105900145.
> Revert "Modify backup script to comment out set -eu (#3597)"

- src/main/java/ti4/map/helper/GameHelper.java
- src/main/java/ti4/migration/DataMigrationManager.java
- src/main/java/ti4/service/statistics/MatchmakingRatingService.java
- src/main/java/ti4/website/model/stats/GameStatsDashboardPayload.java
Introduced GameHelper utility class to centralize and standardize game creation date parsing and formatting. Updated DataMigrationManager and GameStatsDashboardPayload to use the new helper. Improved sorting in MatchmakingRatingService by adding a secondary sort on game name and ensured player lists are sorted for tie handling.
> Refactor date parsing with GameHelper utility

- src/main/java/ti4/helpers/Helper.java
- src/main/java/ti4/service/game/CreateGameService.java
make it last longer and increase user count to handle suspicion that when a new server is opened, many folks who aren't in the existing game will use that game's link
> beef up the new server invite

- src/main/java/ti4/message/logging/BotLogger.java
to match bot startup messages posting to Info
> switch creation of bot-log webhook from Error to Info log

- src/main/java/ti4/map/Game.java
- src/main/java/ti4/map/Player.java
- src/main/java/ti4/website/AsyncTi4WebsiteHelper.java
- src/main/java/ti4/website/model/WebPlayerArea.java
to add support for channel links on web, per https://github.com/AsyncTI4/ti4_web_new/issues/11
> add tabletalk/actions/cardsInfo jumplinks to webdata

- src/main/java/ti4/buttons/handlers/actioncards/ActionCardDeck2ButtonHandler.java
Simplifies the process of revealing the top card of each explore deck and handling relic fragments. Now, the code draws and processes the card in a single step, updates the message output for clarity, and removes redundant deck access.
> Refactor acd2 Tomb Raiders

- .github/workflows/generate-data.yml
- .gitignore
- src/main/java/ti4/helpers/Helper.java
- src/main/java/ti4/model/AttachmentModel.java
- src/main/java/ti4/model/TileModel.java
- src/main/java/ti4/model/TokenModel.java
- src/main/resources/data/relics/absol.json
- src/main/resources/data/relics/codexii.json
- src/main/resources/data/relics/codexiv.json
- src/main/resources/data/relics/dane_leaks.json
- src/main/resources/data/relics/ds.json
- src/main/resources/data/relics/pok.json
- src/main/resources/data/relics/sigma.json
- src/main/resources/data/technologies/absol.json
- src/main/resources/data/technologies/ds.json
- src/main/resources/data/technologies/flagshipping.json
- src/main/resources/data/technologies/pok.json
- src/main/resources/data/units/absol.json
- src/main/resources/data/units/baseUnits.json
- src/main/resources/data/units/ds.json
- src/main/resources/data/units/flagshipping.json
- src/main/resources/data/units/keleres.json
- src/main/resources/data/units/pok.json
This reverts commit c2293cc312215d20cec64df8a1a62891dfcaa8ac, reversing changes made to 10ce5d3f422217ec42d3e46af54fcd5490308963.
> Revert "Merge pull request #3747 from AsyncTI4/image-changes"
